/**
 * Audio Studio Tool Definitions
 *
 * Defines MCP tools for managing audio overviews (podcast-style summaries)
 * generated by NotebookLM's Audio Overview feature.
 */

import type { Tool } from '@modelcontextprotocol/sdk/types.js';

/**
 * Get Audio Status tool
 */
export const getAudioStatusTool: Tool = {
  name: 'get_audio_status',
  title: 'Get Audio Status',
  description:
    'Check the status of the audio overview for a notebook. ' +
    'Returns whether audio exists, is generating, or is ready to play.',
  inputSchema: {
    type: 'object',
    properties: {
      notebook_id: {
        type: 'string',
        description:
          'The notebook ID to check audio status for. If not provided, uses the currently selected notebook.',
      },
    },
    required: [],
  },
};

/**
 * Create Audio tool
 */
export const createAudioTool: Tool = {
  name: 'create_audio',
  title: 'Create Audio Overview',
  description:
    'Generate a new audio overview (podcast-style summary) for a notebook. ' +
    'The audio is created by two AI hosts discussing the content. ' +
    'Generation takes a few minutes. Use get_audio_status to check progress.',
  inputSchema: {
    type: 'object',
    properties: {
      notebook_id: {
        type: 'string',
        description:
          'The notebook ID to create audio for. If not provided, uses the currently selected notebook.',
      },
      custom_instructions: {
        type: 'string',
        description:
          'Optional custom instructions for the audio generation. ' +
          'Example: "Focus on the main arguments" or "Explain concepts for beginners".',
      },
      focus_topics: {
        type: 'array',
        items: { type: 'string' },
        description:
          'Optional list of topics to focus on in the audio.',
      },
      target_audience: {
        type: 'string',
        enum: ['general', 'expert', 'student'],
        description:
          'Target audience for the audio. Affects tone and complexity. ' +
          'Default is "general".',
      },
      wait_for_completion: {
        type: 'boolean',
        description:
          'If true, wait for audio generation to complete before returning. ' +
          'Default is false (returns immediately after starting generation).',
      },
    },
    required: [],
  },
};

/**
 * Update Audio tool
 */
export const updateAudioTool: Tool = {
  name: 'update_audio',
  title: 'Update Audio Overview',
  description:
    'Re-generate the audio overview with new instructions. ' +
    'This deletes the existing audio and creates a new one.',
  inputSchema: {
    type: 'object',
    properties: {
      notebook_id: {
        type: 'string',
        description:
          'The notebook ID to update audio for. If not provided, uses the currently selected notebook.',
      },
      custom_instructions: {
        type: 'string',
        description:
          'New custom instructions for the audio generation.',
      },
      focus_topics: {
        type: 'array',
        items: { type: 'string' },
        description:
          'New list of topics to focus on.',
      },
      target_audience: {
        type: 'string',
        enum: ['general', 'expert', 'student'],
        description:
          'New target audience for the audio.',
      },
    },
    required: [],
  },
};

/**
 * Delete Audio tool
 */
export const deleteAudioTool: Tool = {
  name: 'delete_audio',
  title: 'Delete Audio Overview',
  description:
    'Delete the audio overview for a notebook. ' +
    'This permanently removes the generated audio.',
  inputSchema: {
    type: 'object',
    properties: {
      notebook_id: {
        type: 'string',
        description:
          'The notebook ID to delete audio for. If not provided, uses the currently selected notebook.',
      },
    },
    required: [],
  },
};

/**
 * Download Audio tool
 */
export const downloadAudioTool: Tool = {
  name: 'download_audio',
  title: 'Get Audio Download URL',
  description:
    'Get the download URL for the audio overview. ' +
    'Returns a URL that can be used to download or play the audio file. ' +
    'The URL is temporary and may expire.',
  inputSchema: {
    type: 'object',
    properties: {
      notebook_id: {
        type: 'string',
        description:
          'The notebook ID to get audio URL for. If not provided, uses the currently selected notebook.',
      },
    },
    required: [],
  },
};

/**
 * All audio studio tools
 */
export const studioTools: Tool[] = [
  getAudioStatusTool,
  createAudioTool,
  updateAudioTool,
  deleteAudioTool,
  downloadAudioTool,
];

/**
 * Studio tool names for filtering
 */
export const studioToolNames = studioTools.map((t) => t.name);
