/**
 * Type definitions for NotebookLM Internal API
 *
 * These types are based on reverse-engineering the NotebookLM web app's
 * communication with the batchexecute endpoint.
 */

// ============================================================================
// Request Types
// ============================================================================

/**
 * A single RPC request in a batchexecute call
 */
export interface RPCRequest {
  /** The RPC method ID (e.g., 'wXbhsf' for list notebooks) */
  rpcId: string;
  /** Arguments for the RPC call - typically nested arrays */
  args: unknown[];
  /** Optional request ID for tracking */
  requestId?: string;
}

/**
 * Configuration for an API request
 */
export interface APIRequestConfig {
  /** Cookies for authentication */
  cookies: Cookie[];
  /** CSRF token (extracted from page) */
  csrfToken?: string;
  /** Request timeout in milliseconds */
  timeout?: number;
}

/**
 * Cookie structure matching Playwright's Cookie interface
 */
export interface Cookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires?: number;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: 'Strict' | 'Lax' | 'None';
}

// ============================================================================
// Response Types
// ============================================================================

/**
 * Parsed response from a batchexecute call
 */
export interface BatchExecuteResponse {
  /** Whether the response was successful overall */
  success: boolean;
  /** Individual responses keyed by RPC ID or index */
  responses: Map<string, RPCResponse>;
  /** Raw response text for debugging */
  rawResponse?: string;
  /** Error message if overall request failed */
  error?: string;
}

/**
 * Response from a single RPC call
 */
export interface RPCResponse {
  /** Whether this specific RPC succeeded */
  success: boolean;
  /** Parsed data from the response */
  data?: unknown;
  /** Error message if RPC failed */
  error?: string;
  /** Raw response array for debugging */
  rawData?: unknown[];
}

// ============================================================================
// Notebook Types
// ============================================================================

/**
 * Notebook as returned from the API
 */
export interface APINotebook {
  /** Unique notebook ID (used in URLs) */
  id: string;
  /** Display title of the notebook */
  title: string;
  /** Creation timestamp (microseconds since epoch) */
  createdAt?: number;
  /** Last modified timestamp (microseconds since epoch) */
  modifiedAt?: number;
  /** Thumbnail URL if available */
  thumbnailUrl?: string;
  /** Number of sources in the notebook */
  sourceCount?: number;
  /** Whether the notebook is shared */
  isShared?: boolean;
}

/**
 * Request to create a new notebook
 */
export interface CreateNotebookRequest {
  /** Optional title for the notebook (defaults to "Untitled notebook") */
  title?: string;
}

/**
 * Request to rename a notebook
 */
export interface RenameNotebookRequest {
  /** Notebook ID to rename */
  notebookId: string;
  /** New title for the notebook */
  title: string;
}

// ============================================================================
// Source Types
// ============================================================================

/**
 * Source types supported by NotebookLM
 */
export type SourceType =
  | 'url'           // Web URL
  | 'text'          // Pasted text
  | 'pdf'           // PDF file
  | 'youtube'       // YouTube video
  | 'drive'         // Google Drive file
  | 'audio'         // Audio file
  | 'slides';       // Google Slides

/**
 * Source as returned from the API
 */
export interface APISource {
  /** Unique source ID */
  id: string;
  /** Display title of the source */
  title: string;
  /** Type of source */
  type: SourceType;
  /** Original URL for URL/YouTube/Drive sources */
  url?: string;
  /** Processing status */
  status: 'processing' | 'ready' | 'error';
  /** Error message if processing failed */
  error?: string;
  /** Creation timestamp */
  createdAt?: number;
  /** Summary generated by NotebookLM */
  summary?: string;
  /** Content preview (first few characters) */
  preview?: string;
}

/**
 * Request to add a URL source
 */
export interface AddURLSourceRequest {
  /** Notebook ID to add source to */
  notebookId: string;
  /** URL to fetch and add */
  url: string;
}

/**
 * Request to add a text source
 */
export interface AddTextSourceRequest {
  /** Notebook ID to add source to */
  notebookId: string;
  /** Title for the source */
  title: string;
  /** Text content to add */
  content: string;
}

/**
 * Request to add a YouTube source
 */
export interface AddYouTubeSourceRequest {
  /** Notebook ID to add source to */
  notebookId: string;
  /** YouTube video URL */
  url: string;
}

/**
 * Request to add a Google Drive source
 */
export interface AddDriveSourceRequest {
  /** Notebook ID to add source to */
  notebookId: string;
  /** Google Drive file ID or URL */
  fileId: string;
}

// ============================================================================
// Audio Studio Types
// ============================================================================

/**
 * Audio overview status
 */
export type AudioStatus = 'not_created' | 'generating' | 'ready' | 'error';

/**
 * Audio overview configuration
 */
export interface AudioConfig {
  /** Custom instructions for the audio generation */
  customInstructions?: string;
  /** Target length in minutes (approximate) */
  targetLength?: number;
  /** Voice/style preferences */
  style?: 'conversational' | 'formal' | 'educational';
}

/**
 * Audio overview as returned from the API
 */
export interface APIAudioOverview {
  /** Unique audio ID */
  id?: string;
  /** Current status */
  status: AudioStatus;
  /** Audio file URL when ready */
  audioUrl?: string;
  /** Duration in seconds */
  durationSeconds?: number;
  /** Transcript if available */
  transcript?: string;
  /** Error message if generation failed */
  error?: string;
  /** Generation progress (0-100) */
  progress?: number;
}

// ============================================================================
// Content Generation Types
// ============================================================================

/**
 * Types of content that can be generated
 */
export type ContentType =
  | 'faq'
  | 'briefing'
  | 'timeline'
  | 'outline'
  | 'study_guide'
  | 'flashcards'
  | 'quiz'
  | 'mindmap';

/**
 * Generated content response
 */
export interface GeneratedContent {
  /** Type of content generated */
  type: ContentType;
  /** The generated content (markdown formatted) */
  content: string;
  /** Source references used */
  sourceIds?: string[];
}

/**
 * Request to generate content
 */
export interface GenerateContentRequest {
  /** Notebook ID to generate from */
  notebookId: string;
  /** Type of content to generate */
  contentType: ContentType;
  /** Optional custom prompt/instructions */
  customPrompt?: string;
  /** Optional specific source IDs to use (defaults to all) */
  sourceIds?: string[];
}

// ============================================================================
// Research Types
// ============================================================================

/**
 * Discovered source from web research
 */
export interface DiscoveredSource {
  /** URL of the discovered source */
  url: string;
  /** Title of the page */
  title: string;
  /** Brief description/snippet */
  description: string;
  /** Relevance score (0-1) */
  relevance?: number;
  /** Source type (detected) */
  type: SourceType;
}

/**
 * Request to discover sources
 */
export interface DiscoverSourcesRequest {
  /** Notebook ID for context */
  notebookId: string;
  /** Search query */
  query: string;
  /** Maximum number of results */
  maxResults?: number;
}

// ============================================================================
// Q&A Types
// ============================================================================

/**
 * Suggested question from NotebookLM
 */
export interface SuggestedQuestion {
  /** The suggested question text */
  question: string;
  /** Category/topic of the question */
  category?: string;
}

/**
 * Response to a question (from browser or API)
 */
export interface QuestionResponse {
  /** The answer text */
  answer: string;
  /** Source citations */
  citations?: Citation[];
  /** Follow-up suggested questions */
  suggestedQuestions?: SuggestedQuestion[];
}

/**
 * Citation reference in an answer
 */
export interface Citation {
  /** Source ID referenced */
  sourceId: string;
  /** Source title */
  sourceTitle: string;
  /** Specific quote or passage */
  quote?: string;
  /** Page number for PDFs */
  pageNumber?: number;
}

// ============================================================================
// Error Types
// ============================================================================

/**
 * API error with additional context
 */
export interface APIError {
  /** Error code from the API */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Additional details */
  details?: Record<string, unknown>;
  /** Whether the error is retryable */
  retryable: boolean;
}

/**
 * Known API error codes
 */
export const API_ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  NOTEBOOK_NOT_FOUND: 'NOTEBOOK_NOT_FOUND',
  SOURCE_NOT_FOUND: 'SOURCE_NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_REQUEST: 'INVALID_REQUEST',
  SERVER_ERROR: 'SERVER_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  PARSE_ERROR: 'PARSE_ERROR',
  TIMEOUT: 'TIMEOUT',
} as const;

export type APIErrorCode = typeof API_ERROR_CODES[keyof typeof API_ERROR_CODES];
