/**
 * Audio Studio Operations for NotebookLM
 *
 * Provides high-level operations for managing audio overviews
 * (podcast-style summaries) generated by NotebookLM.
 *
 * Features:
 * - Check audio generation status
 * - Create new audio overview
 * - Update audio with custom instructions
 * - Delete existing audio
 * - Download audio files
 */

import { getAPIClient, type NotebookLMAPIClient } from '../api/index.js';
import { initializeAPIClientWithCookies } from '../auth/cookie-store.js';
import { log } from '../utils/logger.js';
import type { AudioStatus } from '../api/types.js';

/**
 * Result of an audio operation
 */
export interface AudioOperationResult {
  success: boolean;
  status?: AudioStatus;
  audioUrl?: string;
  durationSeconds?: number;
  transcript?: string;
  progress?: number;
  error?: string;
  notebookId?: string;
}

/**
 * Options for creating audio overview
 */
export interface CreateAudioOptions {
  /** Notebook ID to create audio for */
  notebookId: string;
  /** Custom instructions for the audio generation */
  customInstructions?: string;
  /** Focus on specific topics */
  focusTopics?: string[];
  /** Target audience (affects tone/complexity) */
  targetAudience?: 'general' | 'expert' | 'student';
}

/**
 * Get an initialized API client
 */
async function getInitializedClient(): Promise<NotebookLMAPIClient | null> {
  const client = getAPIClient();

  if (client.hasValidAuth()) {
    return client;
  }

  const success = await initializeAPIClientWithCookies(client);
  if (!success) {
    log.warning('⚠️  Failed to initialize API client. Please run setup_auth.');
    return null;
  }

  return client;
}

/**
 * Get current audio status for a notebook
 *
 * Returns the current state of the audio overview:
 * - not_created: No audio has been generated
 * - generating: Audio is currently being generated
 * - ready: Audio is ready to play/download
 * - error: Audio generation failed
 */
export async function getAudioStatus(
  notebookId: string
): Promise<AudioOperationResult> {
  const client = await getInitializedClient();
  if (!client) {
    return {
      success: false,
      error: 'API client not initialized. Please run setup_auth first.',
    };
  }

  try {
    log.info(`🎧 Checking audio status for notebook ${notebookId}...`);

    const status = await client.getAudioStatus(notebookId);

    return {
      success: true,
      status: status.status,
      audioUrl: status.audioUrl,
      durationSeconds: status.durationSeconds,
      transcript: status.transcript,
      progress: status.progress,
      error: status.error,
      notebookId,
    };
  } catch (error) {
    return {
      success: false,
      error: `Failed to get audio status: ${error}`,
      notebookId,
    };
  }
}

/**
 * Create/generate a new audio overview
 *
 * Starts the audio generation process. The audio will be
 * ready after some time (typically a few minutes).
 *
 * Note: Only one audio overview can exist per notebook.
 * Creating a new one will replace any existing audio.
 */
export async function createAudio(
  options: CreateAudioOptions
): Promise<AudioOperationResult> {
  const client = await getInitializedClient();
  if (!client) {
    return {
      success: false,
      error: 'API client not initialized. Please run setup_auth first.',
    };
  }

  try {
    log.info(`🎙️ Creating audio for notebook ${options.notebookId}...`);

    // Build custom instructions if provided
    let instructions = options.customInstructions || '';

    if (options.focusTopics && options.focusTopics.length > 0) {
      instructions += ` Focus on these topics: ${options.focusTopics.join(', ')}.`;
    }

    if (options.targetAudience) {
      switch (options.targetAudience) {
        case 'expert':
          instructions += ' Use technical language appropriate for experts.';
          break;
        case 'student':
          instructions += ' Explain concepts clearly for students learning the material.';
          break;
        case 'general':
          instructions += ' Keep explanations accessible for a general audience.';
          break;
      }
    }

    const success = await client.createAudio(
      options.notebookId,
      instructions.trim() || undefined
    );

    if (!success) {
      return {
        success: false,
        error: 'Failed to start audio generation',
        notebookId: options.notebookId,
      };
    }

    return {
      success: true,
      status: 'generating',
      notebookId: options.notebookId,
    };
  } catch (error) {
    return {
      success: false,
      error: `Audio creation failed: ${error}`,
      notebookId: options.notebookId,
    };
  }
}

/**
 * Update audio with new custom instructions
 *
 * Re-generates the audio overview with updated instructions.
 */
export async function updateAudio(
  options: CreateAudioOptions
): Promise<AudioOperationResult> {
  const client = await getInitializedClient();
  if (!client) {
    return {
      success: false,
      error: 'API client not initialized. Please run setup_auth first.',
    };
  }

  try {
    log.info(`🔄 Updating audio for notebook ${options.notebookId}...`);

    // Delete existing audio first
    await client.deleteAudio(options.notebookId);

    // Then create new audio with updated instructions
    return createAudio(options);
  } catch (error) {
    return {
      success: false,
      error: `Audio update failed: ${error}`,
      notebookId: options.notebookId,
    };
  }
}

/**
 * Delete the audio overview for a notebook
 */
export async function deleteAudio(
  notebookId: string
): Promise<AudioOperationResult> {
  const client = await getInitializedClient();
  if (!client) {
    return {
      success: false,
      error: 'API client not initialized. Please run setup_auth first.',
    };
  }

  try {
    log.info(`🗑️ Deleting audio for notebook ${notebookId}...`);

    const success = await client.deleteAudio(notebookId);

    if (!success) {
      return {
        success: false,
        error: 'Failed to delete audio',
        notebookId,
      };
    }

    return {
      success: true,
      status: 'not_created',
      notebookId,
    };
  } catch (error) {
    return {
      success: false,
      error: `Audio deletion failed: ${error}`,
      notebookId,
    };
  }
}

/**
 * Get the download URL for the audio
 *
 * Returns a URL that can be used to download the audio file.
 * The URL is typically temporary and may expire.
 */
export async function getAudioDownloadURL(
  notebookId: string
): Promise<{ success: boolean; url?: string; error?: string }> {
  const client = await getInitializedClient();
  if (!client) {
    return {
      success: false,
      error: 'API client not initialized. Please run setup_auth first.',
    };
  }

  try {
    log.info(`📥 Getting audio download URL for notebook ${notebookId}...`);

    // First check if audio is ready
    const status = await client.getAudioStatus(notebookId);

    if (status.status !== 'ready') {
      return {
        success: false,
        error: `Audio is not ready. Current status: ${status.status}`,
      };
    }

    // If audio URL was returned with status, use it
    if (status.audioUrl) {
      return {
        success: true,
        url: status.audioUrl,
      };
    }

    // Otherwise try to get the URL separately
    const url = await client.getAudioURL(notebookId);

    if (!url) {
      return {
        success: false,
        error: 'Failed to get audio download URL',
      };
    }

    return {
      success: true,
      url,
    };
  } catch (error) {
    return {
      success: false,
      error: `Failed to get audio URL: ${error}`,
    };
  }
}

/**
 * Wait for audio generation to complete
 *
 * Polls the status until audio is ready or fails.
 *
 * @param notebookId - The notebook ID
 * @param timeoutMs - Maximum time to wait (default: 10 minutes)
 * @param pollIntervalMs - How often to check (default: 10 seconds)
 */
export async function waitForAudio(
  notebookId: string,
  timeoutMs: number = 10 * 60 * 1000,
  pollIntervalMs: number = 10 * 1000
): Promise<AudioOperationResult> {
  const startTime = Date.now();

  while (Date.now() - startTime < timeoutMs) {
    const result = await getAudioStatus(notebookId);

    if (!result.success) {
      return result;
    }

    switch (result.status) {
      case 'ready':
        log.success('✅ Audio generation complete!');
        return result;

      case 'error':
        return {
          success: false,
          status: 'error',
          error: result.error || 'Audio generation failed',
          notebookId,
        };

      case 'not_created':
        return {
          success: false,
          status: 'not_created',
          error: 'No audio generation in progress',
          notebookId,
        };

      case 'generating': {
        const elapsed = Math.floor((Date.now() - startTime) / 1000);
        const progress = result.progress || 0;
        log.info(`⏳ Audio generating... (${elapsed}s elapsed, ${progress}% complete)`);
        break;
      }
    }

    // Wait before next poll
    await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));
  }

  return {
    success: false,
    status: 'generating',
    error: 'Timeout waiting for audio generation',
    notebookId,
  };
}

/**
 * Create audio and wait for completion
 *
 * Convenience function that creates audio and waits for it to be ready.
 */
export async function createAudioAndWait(
  options: CreateAudioOptions,
  timeoutMs?: number
): Promise<AudioOperationResult> {
  // Start generation
  const createResult = await createAudio(options);

  if (!createResult.success) {
    return createResult;
  }

  // Wait for completion
  return waitForAudio(options.notebookId, timeoutMs);
}
